# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "nqnamfe1996@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "Deploy Static Site (NextJS App) to AWS S3"
weight = 1
languageName = "English"

[Languages.vi]
title = "Deploy Static Site (NextJS App) to AWS S3"
weight = 2
languageName = "Tiếng Việt"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj/"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Workshop Repository"
identifier = "This repository"
url = "https://github.com/TsuKpa/aws-ws-001-deploy-static-site-to-s3"
weight = 30

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Workshop Repository"
identifier = "Source code"
url = "https://github.com/TsuKpa/aws-ws-001-deploy-static-site-to-s3"
weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true